"""
Prompts for OpenAI Agents
"""

from .profiler_prompts import PROFILER_SYSTEM_PROMPT, PROFILER_USER_PROMPT
from .validator_prompts import VALIDATOR_SYSTEM_PROMPT, VALIDATOR_USER_PROMPT
from .cleaner_prompts import CLEANER_SYSTEM_PROMPT, CLEANER_USER_PROMPT
from .controller_prompts import CONTROLLER_SYSTEM_PROMPT, CONTROLLER_USER_PROMPT

__all__ = [
    'PROFILER_SYSTEM_PROMPT',
    'PROFILER_USER_PROMPT',
    'VALIDATOR_SYSTEM_PROMPT', 
    'VALIDATOR_USER_PROMPT',
    'CLEANER_SYSTEM_PROMPT',
    'CLEANER_USER_PROMPT',
    'CONTROLLER_SYSTEM_PROMPT',
    'CONTROLLER_USER_PROMPT'
]
