global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets: ['flower:5555']

  - job_name: keycloak
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']

rule_files: []
