# Grafana datasource configuration for Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      keepCookies: []
      timeInterval: 10s
      queryTimeout: 60s
      cacheLevel: 'High'
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
